FROM node:20

WORKDIR /app

COPY ./web/package*.json ./
RUN npm install

COPY ./web .

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
