version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: bitnami/postgresql:latest
    container_name: astrocure-postgres-1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: astrocure
      POSTGRES_PASSWORD: cure123
      POSTGRES_DB: cura
    volumes:
      - pgdatacure:/bitnami/postgresql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "4001:4000"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: astrocure
      PG_PASSWORD: supersecreto
      PG_DB: cura
      ADSPOWER_URL: http://host.docker.internal:50325
      DATABASE_URL: postgresql://astrocure:cure123@postgres:5432/cura
    volumes:
      - ./api:/app
      - shared-videos:/videos # Volume compartilhado para salvar vídeos

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    ports:
      - "3010:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4001
    volumes:
      - ./web:/app

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ADSPOWER_URL: http://host.docker.internal:50325
      DATABASE_URL: postgresql://astrocure:cure123@postgres:5432/cura
    volumes:
      - ./api:/app
      - shared-videos:/videos

  # scheduler:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.scheduler
  #   container_name: scheduler
  #   depends_on:
  #     - redis
  #   environment:
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #   volumes:
  #     - ./api:/app

volumes:
  pgdatacure:
  shared-videos:
