version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: astrocure
      POSTGRES_PASSWORD: cure123
      POSTGRES_DB: cura
    volumes:
      - pgdatacure:/bitnami/postgresql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: astrocure
      PG_PASSWORD: supersecreto
      PG_DB: cura
    volumes:
      - ./api:/app

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    ports:
      - "3010:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    volumes:
      - ./web:/app

volumes:
  pgdatacure:
