# Dockerfile.agent
FROM node:20-alpine

WORKDIR /app

# Copia o package.json e o lock para instalar dependências corretamente
COPY ./api/package*.json ./

RUN npm install

# Agora copia o restante da API, depois das dependências instaladas
COPY ./api .

# Expõe a porta que o agente usa
EXPOSE 5050

# Roda o socket do agente
CMD ["node", "sockets/agentSocket.js"]
