version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: bitnami/postgresql:latest
    container_name: astrocure-postgres-1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: astrocure
      POSTGRES_PASSWORD: cure123
      POSTGRES_DB: cura
    volumes:
      - pgdatacure:/bitnami/postgresql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "4001:4000"
    depends_on:
      - redis
      - postgres
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: astrocure
      PG_PASSWORD: cure123
      PG_DB: cura
      ADSPOWER_URL: http://host.docker.internal:50325
      DATABASE_URL: postgresql://astrocure:cure123@postgres:5432/cura
    # REMOVE esse volume pra não quebrar node_modules
    # volumes:
    #   - ./api:/app
    volumes:
      - shared-videos:/videos

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    ports:
      - "3010:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://178.156.135.171:4000

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ADSPOWER_URL: http://host.docker.internal:50325
      DATABASE_URL: postgresql://astrocure:cure123@postgres:5432/cura
    volumes:
      - shared-videos:/videos

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: agent
    ports:
      - "5050:5050"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql://astrocure:cure123@postgres:5432/cura

volumes:
  pgdatacure:
  shared-videos:
