FROM node:20

WORKDIR /app

# Instala o netcat
RUN apt-get update && apt-get install -y netcat-openbsd

COPY ./api/package*.json ./
RUN npm install

COPY ./api .

RUN npx prisma generate

# Script de entrada
COPY ./api/start.sh .
RUN chmod +x ./start.sh

EXPOSE 4000
CMD ["./start.sh"]
