version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: astrocure
      POSTGRES_PASSWORD: cure123
      POSTGRES_DB: cura
    volumes:
      - pgdatacure:/bitnami/postgresql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "4001:4000"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: astrocure
      PG_PASSWORD: cure123
      PG_DB: cura
      DATABASE_URL: postgresql://astrocure:cure123@postgres:5432/cura
    volumes:
      - ./videos:/videos
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npm run seed &&
             npm run dev"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    ports:
      - "3010:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4001

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    depends_on:
      - api
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql://astrocure:cure123@postgres:5432/cura
    volumes:
      - ./videos:/videos
    command: >
      sh -c "npx prisma generate && npm run worker"

volumes:
  pgdatacure:
